packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
minimumReleaseAgeExclude:
  - '@ai-sdk/gateway@4.0.74'
  - '@ai-sdk/mcp@2.0.44'
  - '@ai-sdk/svelte@5.0.92'
  - ai@7.0.92
